version: '3.8'

services:
  # ---------------------------------
  # SERVICE A: CONTENT (MongoDB)
  # ---------------------------------
  mongodb:
    image: mongo:latest
    container_name: content_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ---------------------------------
  # SERVICE B: INTERACTIONS (PostgreSQL)
  # ---------------------------------
  postgres:
    image: postgres:15
    container_name: interaction_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: interaction_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data: